update workflow

diff --git a/.github/workflows/validate-go-binary.yaml b/.github/workflows/validate-go-binary.yaml
--- a/.github/workflows/validate-go-binary.yaml
+++ b/.github/workflows/validate-go-binary.yaml
@@ -16,13 +16,17 @@ jobs:
         make update-contract
       name: Generate go binary
 
-    - name: Compare with master
+    - uses: actions/checkout@v4
+      run: git fetch origin master
+      name: Fetch master branch
+
+    - name: Validate Go binary
       run: |
-        if ! [ -f "${PARSER_BINARY}" ]; then
-          echo "Error: Go binary does not exist. Please run 'make update-contract' to generate the go binary."
+        if ! [ -f "${PARSER_BINARY}" ] && ! [-f "${{ github.workspace }}/${PARSER_BINARY}"]; then
+          echo "Error: Go binary has not been generated on current branch. Please run 'make update-contract' to generate the go binary."
           exit 1
         fi
-        if cmp -s "${PARSER_BINARY}" "${{ github.event.before }}:${PARSER_BINARY}"; then
+        if cmp -s "${{ github.workspace }}/${PARSER_BINARY}" "${PARSER_BINARY}"; then
           echo "Error: Go binary has not been updated on current branch. Please run 'make update-contract' to update the go binary."
           exit 1
         fi
