fix indentation

diff --git a/.github/workflows/validate-go-binary.yaml b/.github/workflows/validate-go-binary.yaml
--- a/.github/workflows/validate-go-binary.yaml
+++ b/.github/workflows/validate-go-binary.yaml
@@ -7,23 +7,23 @@ pr:
     - pkg/parser
 
 jobs:
-check-go-binary:
-  runs-on: ubuntu-latest
-  steps:
-  - uses: actions/checkout@v4
-  - run: |
-      make validate-image-version
-      cp pkg/parser/bin/parser parser
-    name: Generate go binary
+  check-go-binary:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v4
+    - run: |
+        make validate-image-version
+        cp pkg/parser/bin/parser parser
+      name: Generate go binary
 
-  - name: Checkout master branch
-    uses: actions/checkout@v4
-    with:
-      ref: 'master'
+    - name: Checkout master branch
+      uses: actions/checkout@v4
+      with:
+        ref: 'master'
 
-  - name: Compare go binary with master branch
-    run: |
-      if ! cmp -s pkg/parser/bin/parser parser; then
-        echo "Error: File is different on current branch"
-        exit 1
-      fi
+    - name: Compare go binary with master branch
+      run: |
+        if cmp -s pkg/parser/bin/parser parser; then
+          echo "Error: Go binary has not been updated on current branch. Please run `make update-contract` to update the go binary."
+          exit 1
+        fi
