fix workflow

diff --git a/.github/workflows/validate-go-binary.yaml b/.github/workflows/validate-go-binary.yaml
--- a/.github/workflows/validate-go-binary.yaml
+++ b/.github/workflows/validate-go-binary.yaml
@@ -22,6 +22,10 @@ jobs:
 
     - name: Compare go binary with master branch
       run: |
+        if ! [ -f "pkg/parser/bin/parser" ]; then
+          echo "Error: Go binary does not exist. Please run 'make update-contract' to generate the go binary."
+          exit 1
+        fi
         if ! cmp -s pkg/parser/bin/parser parser; then
           echo "Error: Go binary has not been updated on current branch. Please run 'make update-contract' to update the go binary."
           exit 1
